#!/usr/bin/env bash

echo "############################################"
echo "Starting StateLink                          "
echo "############################################"

vivado -mode tcl -nolog -nojournal -source `dirname "$0"`/HW/StateLink_Init.tcl -quiet